/*MIT License

Copyright (c) 2018 Michael Tepfer

Permission is hereby granted, free of charge, to any person obtaining a copy
           of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
                                               to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

        The above copyright notice and this permission notice shall be included in all
                                                       copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
                                                         AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.*/

#ifndef ENUM_GROUP_FOR_EACH_MACRO_H
#define ENUM_GROUP_FOR_EACH_MACRO_H

/**
 * This file contains a macro that acts as a for each to iterate over variadic arguments
 * Based on this link here
 * @link https://codecraft.co/2014/11/25/variadic-macros-tricks/
 */

#define __GET_NTH_ARG( _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, \
_21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, N, ... ) N

//<editor-fold desc="_FE_x">
#define _FE_0( _CALL, ... )
#define _FE_1( _CALL, NEXT_VALUE ) _CALL(NEXT_VALUE)
#define _FE_2( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_1(_CALL, __VA_ARGS__)
#define _FE_3( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_2(_CALL, __VA_ARGS__)
#define _FE_4( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_3(_CALL, __VA_ARGS__)
#define _FE_5( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_4(_CALL, __VA_ARGS__)
#define _FE_6( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_5(_CALL, __VA_ARGS__)
#define _FE_7( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_6(_CALL, __VA_ARGS__)
#define _FE_8( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_7(_CALL, __VA_ARGS__)
#define _FE_9( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_8(_CALL, __VA_ARGS__)
#define _FE_10( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_9(_CALL, __VA_ARGS__)
#define _FE_11( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_10(_CALL, __VA_ARGS__)
#define _FE_12( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_11(_CALL, __VA_ARGS__)
#define _FE_13( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_12(_CALL, __VA_ARGS__)
#define _FE_14( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_13(_CALL, __VA_ARGS__)
#define _FE_15( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_14(_CALL, __VA_ARGS__)
#define _FE_16( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_15(_CALL, __VA_ARGS__)
#define _FE_17( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_16(_CALL, __VA_ARGS__)
#define _FE_18( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_17(_CALL, __VA_ARGS__)
#define _FE_19( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_18(_CALL, __VA_ARGS__)
#define _FE_20( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_19(_CALL, __VA_ARGS__)
#define _FE_21( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_20(_CALL, __VA_ARGS__)
#define _FE_22( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_21(_CALL, __VA_ARGS__)
#define _FE_23( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_22(_CALL, __VA_ARGS__)
#define _FE_24( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_23(_CALL, __VA_ARGS__)
#define _FE_25( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_24(_CALL, __VA_ARGS__)
#define _FE_26( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_25(_CALL, __VA_ARGS__)
#define _FE_27( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_26(_CALL, __VA_ARGS__)
#define _FE_28( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_27(_CALL, __VA_ARGS__)
#define _FE_29( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_28(_CALL, __VA_ARGS__)
#define _FE_30( _CALL, NEXT_VALUE, ... ) _CALL(NEXT_VALUE) _FE_29(_CALL, __VA_ARGS__)
//</editor-fold>

#define FOR_EACH( MACRO, ... ) \
__GET_NTH_ARG("ignored", ##__VA_ARGS__, _FE_30, _FE_29, _FE_28, _FE_27, _FE_26, _FE_25, _FE_24, _FE_23, _FE_22, \
_FE_21, _FE_20, _FE_19, _FE_18, _FE_17, _FE_16, _FE_15, _FE_14, _FE_13, _FE_12, _FE_11, _FE_10, _FE_9, _FE_8, _FE_7, \
_FE_6, _FE_5, _FE_4, _FE_3, _FE_2, _FE_1, _FE_0) \
(MACRO, ##__VA_ARGS__)

//<editor-fold desc="_FE_x_WITH_EXTRA">
#define _FE_0_WITH_EXTRA( _CALL, ... )
#define _FE_1_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE ) _CALL(EXTRA, NEXT_VALUE)
#define _FE_2_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_1_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_3_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_2_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_4_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_3_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_5_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_4_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_6_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_5_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_7_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_6_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_8_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_7_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_9_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_8_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_10_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_9_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_11_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_10_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_12_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_11_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_13_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_12_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_14_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_13_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_15_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_14_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_16_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_15_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_17_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_16_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_18_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_17_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_19_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_18_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_20_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_19_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_21_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_20_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_22_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_21_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_23_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_22_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_24_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_23_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_25_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_24_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_26_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_25_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_27_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_26_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_28_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_27_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_29_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_28_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
#define _FE_30_WITH_EXTRA( _CALL, EXTRA, NEXT_VALUE, ... ) _CALL(EXTRA, NEXT_VALUE) _FE_29_WITH_EXTRA(_CALL, EXTRA, __VA_ARGS__)
//</editor-fold>

#define FOR_EACH_WITH_EXTRA( MACRO, EXTRA, ... ) \
__GET_NTH_ARG("ignored", ##__VA_ARGS__, _FE_30_WITH_EXTRA, _FE_29_WITH_EXTRA, _FE_28_WITH_EXTRA, _FE_27_WITH_EXTRA, \
_FE_26_WITH_EXTRA, _FE_25_WITH_EXTRA, _FE_24_WITH_EXTRA, _FE_23_WITH_EXTRA, _FE_22_WITH_EXTRA, _FE_21_WITH_EXTRA, \
_FE_20_WITH_EXTRA, _FE_19_WITH_EXTRA, _FE_18_WITH_EXTRA, _FE_17_WITH_EXTRA, _FE_16_WITH_EXTRA, _FE_15_WITH_EXTRA, \
_FE_14_WITH_EXTRA, _FE_13_WITH_EXTRA, _FE_12_WITH_EXTRA, _FE_11_WITH_EXTRA, _FE_10_WITH_EXTRA, _FE_9_WITH_EXTRA, \
_FE_8_WITH_EXTRA, _FE_7_WITH_EXTRA, _FE_6_WITH_EXTRA, _FE_5_WITH_EXTRA, _FE_4_WITH_EXTRA, _FE_3_WITH_EXTRA, \
_FE_2_WITH_EXTRA, _FE_1_WITH_EXTRA, _FE_0_WITH_EXTRA) \
(MACRO, EXTRA, ##__VA_ARGS__)

#endif //ENUM_GROUP_FOR_EACH_MACRO_H
